# Generated by Django 5.1.1 on 2024-09-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField()),
                ('CycleTime', models.TimeField()),
                ('StartTime', models.TimeField()),
                ('StopTime', models.TimeField()),
                ('Input_data', models.FloatField()),
                ('Output_data', models.FloatField()),
                ('Power_Consume', models.FloatField()),
            ],
        ),
    ]
