# Generated by Django 5.1.1 on 2024-09-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urban_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cummulative_report_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_data', models.DateTimeField()),
                ('Cycle_No', models.IntegerField()),
                ('Cycle_start_timestamp', models.DateTimeField()),
                ('Cycle_complete_timestamp', models.DateTimeField()),
                ('waste_add', models.FloatField()),
                ('power_consumed', models.FloatField()),
                ('compost_removed', models.FloatField()),
            ],
        ),
    ]
